### ISSUE TITLE
Final checklist for Monday morning 5/8/2023

### ISSUE THREAD

**Issue by patudom** [cosmicds/hubbleds#246]
- [ ] Deploy latest code from cosmicds & hubbleds
- [ ] Update notebook so show_team_interface = False and allow_advancing = False; update_db = True
- [ ] Make sure notebook is in the correct directory (tmp?)
- [ ] Do we need to include a fake student in the rogers_astro class?
- [ ] If we have time, make 3-4 new beta students in 1 class, so we can verify that all the latest code changes are ok.

**Comment by patudom** [comment]
- [ ] There's something weird with one of the class data sets. I was trying to go through and get rid of some of my bad  data points (which had way too large distances) from the beta test, and I think I succeeded in fixing the points themselves, but now the class slider label has the wrong age for this class and it is sorted in the wrong place on the slider. (The best fit line has the correct age). It would be good if we could figure out what's happening with this and fix it before class, but if not, hopefully no one will get this far anyway.

<img width="1271" alt="Screen Shot 2023-05-08 at 12 05 10 AM" src="https://user-images.githubusercontent.com/12750048/236731949-ae9ee804-63ce-4399-bf72-886cbe965460.png">
